[toolchain]

[test]
startup_wait = 10000  # Increase this value if needed


[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_marketplaces = "A1vz36S5TVrdT7F4P3aHC3Hgg8sr6EGSvwGXKBoqUMsp"

[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

